#=======================================
# AntiCommandTab v3.4 by libraryaddict   
#    new and improved by sgtcaze         
#      Dev Builds ci.playmc.cc          
#=======================================
# Usage:
# %player - Replaces with the player's list name
# &a-f/0-9 - Replaces with color codes
#=======================================

# You can choose to disable command protection here:
BlockPlugins: true
BlockVersion: true
BlockAbout: true
BlockQuestionMark: true
 
# Sent to players attempting use /plugins and /pl
Plugins: '&cYou do not have permission.'

# Sent to players attempting use /?
QuestionMark: '&dYou do not have permission.'

# Sent to players attempting use /about
About: '&eYou do not have permission.'

# Sent to players attempting use /version and /ver
Version: '&aYou do not have permission.'